pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tag: '$(build.buildId)'

steps:
- script: docker login -u $(dockerId) -p $(dockerPass)
  displayName: "docker login"
# Maven build
- task: ShellScript@2
  inputs:
    scriptPath: 'web-vue/build.sh'
# web-vue
#- script: docker build -t $(dockerNamespace)/web-vue web-vue
#  displayName: 'docker build web-vue'
- script: docker tag $(dockerNamespace)/web-vue $(dockerNamespace)/web-vue:$(tag)
  displayName: 'docker tag $(dockerNamespace)/web-vue:$(tag)'
- script: docker push $(dockerNamespace)/web-vue:$(tag)
  displayName: 'docker push $(dockerNamespace)/web-vue:$(tag)'
- script: docker push $(dockerNamespace)/web-vue:latest
  displayName: 'docker push $(dockerNamespace)/web-vue:latest'
