pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tag: '$(build.buildId)'

steps:
- script: docker login -u $(dockerId) -p $(dockerPass)
  displayName: "docker login"
- script: web-vue/build.sh
  displayName: 'docker build web-vue'
- script: docker tag $(dockerNamespace)/web-vue $(dockerNamespace)/web-vue:$(tag)
  displayName: 'docker tag $(dockerNamespace)/web-vue:$(tag)'
- script: docker push $(dockerNamespace)/web-vue:$(tag)
  displayName: 'docker push $(dockerNamespace)/web-vue:$(tag)'
- script: docker push $(dockerNamespace)/web-vue:latest
  displayName: 'docker push $(dockerNamespace)/web-vue:latest'
