micronaut:
  application:
    name: product-service
  server:
    port: ${SERVICE_PORT:-1}
  metrics:
    enabled: true
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/products-demo"
    cluster:
      maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
---
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  metrics:
    enabled: true
    sensitive: false
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.

