kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  labels:
    srv: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: mongo
  template:
    metadata:
      labels:
        srv: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5