kind: Service
apiVersion: v1
metadata:
  name: zookeeper
  labels:
    srv: zookeeper
spec:
  type: ClusterIP
  selector:
    srv: zookeeper
  ports:
  - name: zk
    protocol: TCP
    port: 2181
    targetPort: 2181
