version: '2'

services:
  jsreport:
    image: jsreport/jsreport
    container_name: jsreport
    hostname: jsreport
    ports:
      - 5488:5488
  consul:
    image: consul
    container_name: consul
    hostname: consul
    ports:
      - 8500:8500
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin
    ports:
      - 9411:9411
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
  zookeeper:
    image: 'bitnami/zookeeper:3.4.12'
    container_name: zookeeper
    hostname: zookeeper
    ports:
    - 2181:2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: "bitnami/kafka:2.0.0"
    container_name: kafka-server
    hostname: kafka-server
    ports:
    - 9092:9092
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
  kafka-manager:
    image: "deric/kafka-manager:1.3.3.18"
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
    - 9000:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
    - zookeeper
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - 9200:9200
