micronaut:
  application:
    name: chat-service
  server:
    port: ${SERVICE_PORT:8787}
  metrics:
    enabled: true
---
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  metrics:
    enabled: true
    sensitive: false
